# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: xhocquet.info
email: xhocquet@gmail.com
description:
baseurl: /
url: https://xhocquet.github.io

# Personal information
author: Xavier Hocquet
name: Xavier Hocquet

# Disqus
disqus_shortname: xhocquetinfo

# Pagination
paginate: 10

collections:
  recipes:
    output: true
    sort_by: title
  reflections:
    output: true
  reviews:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: home


theme: minima
plugins:
  - jekyll-feed

minima:
  social_links:
    - title: GitHub
      icon: github-alt
      url: "https://github.com/xhocquet"
    - title: LinkedIn
      icon: linkedin-in
      url: "https://linkedin.com/in/xhocquet"
    - title: CV
      icon: readme
      url: "https://docs.google.com/document/d/1NkF057FcXJHJ0WFpiFlqJ3t80GODgBVdQNpsUFtZEBs/preview"
    - title: HackerNews
      icon: hacker-news
      url: "https://news.ycombinator.com/user?id=meesles"


disable_disk_cache: true
