# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: xhocquet.info
email: xhocquet@gmail.com
description:
baseurl: /
url: https://xhocquet.info

# Personal information
author: Xavier Hocquet
name: Xavier Hocquet

# Disqus
disqus_shortname: xhocquetinfo

# Pagination
paginate: 10

collections:
  recipes:
    output: true
    sort_by: title
  reflections:
    output: true
  reviews:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: home


# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  social_links:
    - title: GitHub
      icon: github-alt
      url: "https://github.com/xhocquet"
    - title: LinkedIn
      icon: linkedin-in
      url: "https://linkedin.com/in/xhocquet"
    - title: CV
      icon: readme
      url: "https://docs.google.com/document/d/1NkF057FcXJHJ0WFpiFlqJ3t80GODgBVdQNpsUFtZEBs/preview"
    - title: HackerNews
      icon: hacker-news
      url: "https://news.ycombinator.com/user?id=meesles"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disable_disk_cache: true
